bundler_args: --without development
stack: docker
rvm:
  - 1.9.3
script: bundle exec rspec
notifications:
  email: false
addons:
  firefox: "17.0"
  postgresql: "9.2"
services:
  - redis
  - elasticsearch
  - riak
  - rabbitmq
  - memcached
